# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: byoman

before:
  hooks:
    - go mod tidy

builds:
  - id: byoman
    main: .
    binary: byoman
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: sahil87
    name: byoman
  prerelease: auto
  mode: replace
  footer: |
    ## Installation

    ### macOS / Linux
    ```bash
    curl -sSfL https://raw.githubusercontent.com/sahil87/byoman/main/install.sh | sh
    ```

    ### Go install
    ```bash
    go install github.com/sahil87/byoman@{{.Tag}}
    ```

    ### Manual
    Download the appropriate archive for your platform from the assets below.
